package fr.epita.bank.launcher;

import fr.epita.bank.datamodel.*;
import fr.epita.bank.services.AccountService;

import java.time.LocalDate;
import java.util.Date;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World");

        //usecase 1 :
        // a. create a customer
        // b. create a savings account with 300 €, interest rate: 3%
        // c. perform a withdraw of 200€
        // d. compute the gain generated by the interests
        int amount = 300;
        int rate = 3;


        Customer customer = new Customer();
        customer.setName("John");
        customer.setAddress("Paris");

        SavingsAccount savingsAccount = new SavingsAccount(customer, amount, rate );


        savingsAccount.setBalance(savingsAccount.getBalance() - 200);

        double gain = savingsAccount.getBalance() * savingsAccount.getInterestRate() / (double) 100;

        // 2. buy stocks
        Stock stock = new Stock();

        // a. define a stock "GOLD", value: 800€ / unit
        stock.setName("GOLD");
        stock.setUnitPrice(800);

        // b. initialize an investment account linked to the same customer
        // c. set the balance to 3000€
        InvestmentAccount investmentAccount = new InvestmentAccount(customer, 3000 );
        investmentAccount.setCustomer(customer);


        // d. buy 3 units of GOLD
        StockOrder stockOrder = AccountService.buyStocks(investmentAccount, stock, 3);

        // e. GOLD price has increased (+300€ per unit)
        stock.setUnitPrice(stock.getUnitPrice() + 300);

        // f. compute the added value if the units are sold.


        int difference = AccountService.computeAddedValue(stockOrder);
        System.out.println("Increase rate: " + AccountService.computeIncreaseRate(stockOrder));

        // g. apply a commission of 5% on added values to estimate the bank commission on the transaction.
        double commission = difference * 0.05;
        System.out.println("Commission: " + commission);
        investmentAccount.setBalance(Math.round(investmentAccount.getBalance()  + stockOrder.getUnitPrice() * stockOrder.getQuantity()  - commission));
        //TODO implement the sellStocks from accountService and replace here.




    }

}
