package fr.epita.bank.launcher;

import fr.epita.bank.datamodel.Customer;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World");

        //usecase 1 :
        // a. create a customer
        // b. create a savings account with 300 €, interest rate: 3%
        // c. perform a withdraw of 200€
        // d. compute the gain generated by the interests
        int amount = 300;
        int rate = 3;


        Customer customer = new Customer();
        customer.setName("John");
        customer.setAddress("Paris");


    }
}
