package fr.epita.bank.launcher;

import fr.epita.bank.datamodel.*;
import fr.epita.bank.services.AccountService;

import java.time.LocalDate;
import java.util.Date;

public class Main {

    public static void main(String[] args) {
        System.out.println("Hello World");

        //usecase 1 :
        // a. create a customer
        // b. create a savings account with 300 €, interest rate: 3%
        // c. perform a withdraw of 200€
        // d. compute the gain generated by the interests
        int amount = 300;
        int rate = 3;


        Customer customer = new Customer();
        customer.setName("John");
        customer.setAddress("Paris");

        SavingsAccount savingsAccount = new SavingsAccount();
        savingsAccount.setBalance(amount);
        savingsAccount.setInterestRate(rate);
        savingsAccount.setCustomer(customer);

        savingsAccount.setBalance(savingsAccount.getBalance() - 200);

        double gain = savingsAccount.getBalance() * savingsAccount.getInterestRate() / (double) 100;

        // 2. buy stocks
        Stock stock = new Stock();

        // a. define a stock "GOLD", value: 800€ / unit
        stock.setName("GOLD");
        stock.setUnitPrice(800);

        // b. initialize an investment account linked to the same customer
        InvestmentAccount investmentAccount = new InvestmentAccount();
        investmentAccount.setCustomer(customer);

        // c. set the balance to 3000€
        investmentAccount.setBalance(3000);

        // d. buy 3 units of GOLD
        StockOrder stockOrder = AccountService.buyStocks(investmentAccount, stock, 3);

        // e. GOLD price has increased (+300€ per unit)
        stock.setUnitPrice(stock.getUnitPrice() + 300);

        // f. compute the added value if the units are sold.
        int boughtUnitPrice = stockOrder.getUnitPrice();
        int currentUnitPrice = stock.getUnitPrice();

        int difference = (currentUnitPrice - boughtUnitPrice) * stockOrder.getQuantity();
        double increaseRate = difference *100d / boughtUnitPrice;

        System.out.println("Increase rate: " + increaseRate);

        // g. apply a commission of 5% on added values to estimate the bank commission on the transaction.
        double commission = difference * 0.05;
        System.out.println("Commission: " + commission);
        investmentAccount.setBalance(Math.round(investmentAccount.getBalance()  + currentUnitPrice * stockOrder.getQuantity()  - commission));





    }

    private static StockOrder getStockOrder(Stock stock, InvestmentAccount investmentAccount) {
        StockOrder stockOrder = new StockOrder();
        stockOrder.setQuantity(3);
        stockOrder.setUnitPrice(stock.getUnitPrice());
        stockOrder.setTimestamp(new Date().getTime());
        stockOrder.setStock(stock);
        stockOrder.setInvestmentAccount(investmentAccount);

        investmentAccount.setBalance(investmentAccount.getBalance() - stockOrder.getQuantity() * stockOrder.getUnitPrice());
        return stockOrder;
    }
}
